// Auto-generated by `wrangler types`
// Run `npm run types` to regenerate.

interface Env {
  DB: D1Database;
  MEDIA_BUCKET: R2Bucket;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  R2_ACCOUNT_ID: string;
}
